###############################################################
# Home Assistant Config 
###############################################################
homeassistant:
  name: Moss/Bailey Home
  latitude: !secret home_lat
  longitude: !secret home_long
# Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 238
# metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis
# Cutomized Entities  
  customize: !include_dir_merge_named customizations

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Enables configuration and UI
config:
http:
  api_password: !secret HA_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3
  base_url: !secret base_url
  
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
#######################################################
# End Home Assistant Main Server Config
#######################################################


###################################################
# These are the actual IoT Devices
###################################################
light: !include lights.yaml
switch: !include rf_switch.yaml
sensor: !include sensors.yaml
#binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
  
###################################################
# Automation resources directories
###################################################
group: !include_dir_merge_named groups
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
notify: !include_dir_merge_list notifications
mqtt:
  broker: !secret cloudmqtt_server
  port: !secret cloudmqtt_port
  username: !secret cloudmqtt_user
  password: !secret cloudmqtt_password
  
# Track the sun
sun:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history: !include history_config.yaml

# Media Players
media_player: !include media_players.yaml

# Favorite WEblinks for frontend
weblink: !include weblinks.yaml


# Configure different zones for tracking and Map
zone: !include zones.yaml

#Track Devices for location events Bluetooth and Wifi
device_tracker: !include device_tracker.yaml

# https://ifttt.com/
ifttt:
  key: !secret ifttt_key
  
# Allow Alexa to see home assistant like a hue via rest API
emulated_hue: !include alexa_simple_connection.yaml

# Text to speech
#tts:
#  platform: google



