homeassistant:
  name: Moss/Bailey Home
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 238
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis
# Cutomized Entities  
  customize: !include customize.yaml

# Enables the frontend
frontend:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Enables configuration UI
config:

# Home Assistant Sytem Configs
http:
  api_password: !secret HA_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:
#######################################################
# End Home Assistant Main Server Config
#######################################################


ifttt:
  key: !secret ifttt_key
  
automation: !include automations.yaml

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

history: !include history_config.yaml


###################################################
# These are the IoT Devices
###################################################
switch: !include rf_switch.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
camera: !include cameras.yaml
#####################################################


  
# Allow Alexa to see home assistant like a hue via rest API
emulated_hue: !include alexa_simple_connection.yaml

group: !include groups.yaml
# Configure different zones for tracking and Map
zone: !include zones.yaml

#Track Devices for location events Bluetooth and Wifi
device_tracker: !include device_tracker.yaml

# Media Players
media_player: !include media_players.yaml

# Favorite WEblinks for frontend
weblink: !include weblinks.yaml

# Text to speech
#tts:
#  platform: google



