homeassistant:
  name: Moss/Bailey Home
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 238
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  time_zone: America/Indiana/Indianapolis
  customize: !include customize.yaml
 
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
automation: !include automations.yaml
config:

http:
  api_password: !secret HA_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ip_ban_enabled: True
  login_attempts_threshold: 3
  
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - groups
    entities:
      - sensor.last_boot
      - sensor.date
      - device_tracker.trooperbuild
      - device_tracker.raspberrypi
      - binary_sensor.pir_bedroom
      - device_tracker.amazonecho
      - device_tracker.bedroomfirestick
      - device_tracker.firetv
      
# View all events in a logbook
logbook:

# Track the sun
sun:

ifttt:
  key: !secret ifttt_key
  
# Right now only have RF switches
switch: !include rf_switch.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
light: !include lights.yaml
camera: !include cameras.yaml
zone: !include zones.yaml
  
# Allow Alexa to see home assistant like a hue via rest API
emulated_hue: !include alexa_simple connection.yaml

group: !include groups.yaml

#Track Devices for location events Bluetooth and Wifi
device_tracker: !include device_tracker.yaml

# Media Players
media_player: !include media_players.yaml

weblink: !include weblinks.yaml

#sensor:
#  - platform: snmp
#    host: !secret router_host
#    community: !secret router_community
#    baseoid: 1.3.6.1.4.1.2021.10.1.3.1

# Text to speech
#tts:
#  platform: google



